# -*- coding: utf-8 -*-
"""student_performance.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cZs9Lvf2cJbUPxMNDkJMmOLToos6O8a
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('student_performance.csv')
df.head()

import pandas as pd

df = pd.read_csv('student_performance.csv')
df.head()

df.shape
df.info()
df.describe()
df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

# Performance histogram
plt.hist(df['Performance Index'])
plt.show()

# Study vs Performance
plt.scatter(df['Hours Studied'], df['Performance Index'])
plt.show()

# Gender count
sns.countplot(x='Gender', data=df)
plt.show()

df['Gender'] = df['Gender'].map({'Female':1, 'Male':0}).fillna(-1).astype(int)
df['Tuition'] = df['Tuition'].map({'Yes':1, 'No':0}).fillna(-1).astype(int)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes':1, 'No':0}).fillna(-1).astype(int)

X = df.drop(columns=['Performance Index'])
y = df['Performance Index']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

import seaborn as sns
import matplotlib.pyplot as plt

correlation_matrix = df.corr(numeric_only=True)
display(correlation_matrix)

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of DataFrame df')
plt.show()

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'Mean Squared Error (MSE): {mse:.2f}')
print(f'R-squared (R2): {r2:.2f}')

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2:", r2)

def predict_score(gender, hours, prev, extra, tuition, sleep, papers):

    g = 1 if gender.lower()=='female' else 0
    e = 1 if extra.lower()=='yes' else 0
    t = 1 if tuition.lower()=='yes' else 0

    student = pd.DataFrame([[g,hours,prev,e,t,sleep,papers]], columns=X.columns)

    score = model.predict(student)[0]
    print("Predicted Score:", round(score,1))

predict_score('Female', 8, 85, 'Yes', 'Yes', 7, 5)

results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred.round(1)
})

results.to_csv('student_predictions.csv', index=False)

results.head(10)

within_5 = (abs(results['Actual'] - results['Predicted']) <= 5).mean() * 100
print(f"{within_5:.1f}% predictions are within ±5 marks")

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.plot([10,100],[10,100],'r--')
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

residuals = y_test - y_pred

plt.hist(residuals)
plt.title("Errors")
plt.show()

